const BlogActionTypes = {
	LIKE_BLOG_POST: 'LIKE_BLOG_POST',
	CREATE_BLOG_POST: 'CREATE_BLOG_POST',
	DELETE_BLOG_POST: 'DELETE_BLOG_POST',
	UPDATE_BLOG_POST: 'UPDATE_BLOG_POST',
	FETCH_BLOG_POSTS: 'FETCH_BLOG_POSTS'
};

export default BlogActionTypes;
