const BlogActionTypes = {
	BLOG_POST_SUCCESS: 'BLOG_POST_SUCCESS',
	BLOG_POST_FAILURE: 'BLOG_POST_FAILURE',
	BLOG_POST_ERROR: 'BLOG_POST_ERROR',
	CREATE_BLOG_POST: 'CREATE_BLOG_POST',
	DELETE_BLOG_POST: 'DELETE_BLOG_POST',
	UPDATE_BLOG_POST: 'UPDATE_BLOG_POST',
	FETCH_BLOG_POSTS: 'FETCH_BLOG_POSTS'
};

export default BlogActionTypes;
